# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('action', models.IntegerField(choices=[(0, 'SSH'), (1, 'HTTP')], default=0)),
                ('command', models.TextField()),
                ('parameters', models.TextField(blank=True, help_text='URL params or STDIN', null=True)),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('password', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('action', models.IntegerField(choices=[(0, 'SSH'), (1, 'HTTP')], default=0)),
                ('command', models.TextField()),
                ('parameters', models.TextField(help_text='URL params or STDIN')),
                ('result', models.TextField()),
                ('path', models.CharField(blank=True, max_length=512, null=True)),
                ('username', models.CharField(blank=True, max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='credentials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.JobCredential'),
        ),
    ]
