# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='action',
            field=models.IntegerField(choices=[(0, 'SSH'), (1, 'HTTP'), (2, 'AGENT')], default=0),
        ),
        migrations.AlterField(
            model_name='run',
            name='action',
            field=models.IntegerField(choices=[(0, 'SSH'), (1, 'HTTP'), (2, 'AGENT')], default=0),
        ),
    ]
