# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_organization_allowed_ips'),
        ('jobs', '0002_auto_20170126_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Organization'),
            preserve_default=False,
        ),
    ]
