# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'RUNNING'), (2, 'COMPLETED')], default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='cron_string',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
