# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20170122_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='scheduled',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Scheduled time'),
            preserve_default=False,
        ),
    ]
