# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20170122_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcredential',
            name='created_at',
            field=models.DateTimeField(verbose_name='Date created'),
        ),
    ]
