# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20170122_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='scheduled',
            field=models.DateTimeField(verbose_name='Scheduled time'),
        ),
    ]
