# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20170122_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='return_code',
            field=models.IntegerField(default=-1),
        ),
    ]
