# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='allowed_ips',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
