# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-26 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='type',
            field=models.IntegerField(choices=[(0, b'SSH'), (1, b'HTTP'), (2, b'AGENT')], default=0),
            preserve_default=False,
        ),
    ]
