# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='pid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
