# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-22 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_auto_20170122_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cert',
            field=models.TextField(blank=True, null=True),
        ),
    ]
